docker run -it --rm -v ./nginx/ssl:/etc/letsencrypt certbot/certbot certonly \
	-v \
	--manual \
	--agree-tos \
	--email bernhard@bhnord.com \
	--preferred-challenges dns \
	-d glance.bhnord.com \
	-d mealie.bhnord.com \
	-d paperless.bhnord.com \
	-d chibi.bhnord.com \
	-d bullet.bhnord.com \
	-d tools.bhnord.com
